using static BudgetCentre.PdfRenderer.Theme.PdfThemePrimitives;

namespace BudgetCentre.PdfRenderer.Theme;

internal static class CivicBlueTheme
{
    public static PdfTheme Create() => ClassicTheme.Create() with
    {
        Key = "civic_blue",
        MarginTop = Mm(18),
        MarginRight = Mm(16),
        MarginBottom = Mm(16),
        MarginLeft = Mm(16),
        BookkeepingMarginTop = Mm(14),
        BookkeepingMarginRight = Mm(12),
        BookkeepingMarginBottom = Mm(15),
        BookkeepingMarginLeft = Mm(12),
        TitleFontSize = 19,
        SubtitleFontSize = 8.1f,
        BodyFontSize = 6.95f,
        BookkeepingBodyFontSize = 6.2f,
        BookkeepingHeaderFontSize = 6.05f,
        SectionFill = Rgb(27, 82, 130),
        SectionTextColor = Rgb(255, 255, 255),
        HeaderFill = Rgb(229, 236, 244),
        SummaryFill = Rgb(231, 246, 248),
        BorderColor = Rgb(80, 105, 130),
        AccentColor = Rgb(0, 94, 168),
        WatermarkColor = Rgb(197, 213, 228),
        HeaderMetaPanel = true,
        FooterTopRule = true,
        BudgetTable = new PdfTableVisualSpec
        {
            SectionMarginTop = Mm(5.5f),
            SectionFontSize = 9.7f,
            SectionLineHeight = 1.15f,
            SectionPaddingTop = Mm(0.75f),
            SectionPaddingBottom = Mm(0.7f),
            SectionPaddingHorizontal = Mm(1.35f),
            DateFontSize = 7.1f,
            DateLineHeight = 1.24f,
            DatePaddingTop = Mm(1.4f),
            DatePaddingBottom = Mm(0.85f),
            DatePaddingHorizontal = Mm(1.35f),
            DateUnderline = false,
            DateBorderTopWidth = 0,
            DateBorderBottomWidth = Mm(0.2f),
            HeaderFontSize = 6.9f,
            HeaderLineHeight = 1.18f,
            HeaderPaddingVertical = Mm(0.32f),
            HeaderPaddingHorizontal = Mm(1.35f),
            HeaderDividerWidth = Mm(0.2f),
            HeaderBottomBorderWidth = Mm(0.25f),
            BodyFontSize = 6.95f,
            BodyLineHeight = 1.27f,
            BodyPaddingVertical = Mm(0.32f),
            BodyPaddingHorizontal = Mm(1.35f),
            BodyBottomBorderWidth = Mm(0.15f),
            SummaryTopBorderWidth = Mm(0.45f),
            SummaryFirstTopBorderWidth = Mm(0.45f),
            MoneySecondaryFontSize = 6.15f,
        },
        BookkeepingTable = new PdfTableVisualSpec
        {
            SectionMarginTop = Mm(4.2f),
            SectionFontSize = 8.8f,
            SectionLineHeight = 1.14f,
            SectionPaddingTop = Mm(0.5f),
            SectionPaddingBottom = Mm(0.5f),
            SectionPaddingHorizontal = Mm(1),
            DateFontSize = 6.2f,
            DateLineHeight = 1.2f,
            DatePaddingTop = Mm(0.2f),
            DatePaddingBottom = Mm(0.2f),
            DatePaddingHorizontal = Mm(1),
            DateUnderline = false,
            DateBorderTopWidth = 0,
            DateBorderBottomWidth = Mm(0.2f),
            HeaderFontSize = 6.05f,
            HeaderLineHeight = 1.14f,
            HeaderPaddingVertical = Mm(0.2f),
            HeaderPaddingHorizontal = Mm(1),
            HeaderDividerWidth = Mm(0.2f),
            HeaderBottomBorderWidth = Mm(0.25f),
            BodyFontSize = 6.2f,
            BodyLineHeight = 1.21f,
            BodyPaddingVertical = Mm(0.2f),
            BodyPaddingHorizontal = Mm(1),
            BodyBottomBorderWidth = Mm(0.15f),
            SummaryTopBorderWidth = Mm(0.2f),
            SummaryFirstTopBorderWidth = Mm(0.45f),
            MoneySecondaryFontSize = 5.65f,
        },
        Signature = new PdfSignatureVisualSpec
        {
            FullWidthMm = 178,
            MarginTop = Mm(5.5f),
            SectionTopBorderWidth = Mm(0.35f),
            TitleFontSize = 9.7f,
            TitleLineHeight = 1.15f,
            TitleMinHeightMm = 6,
            TitlePaddingTopMm = 0.8f,
        },
    };
}
