using iText.Kernel.Geom;
using static BudgetCentre.PdfRenderer.Theme.PdfThemePrimitives;

namespace BudgetCentre.PdfRenderer.Theme;

internal static class ClassicTheme
{
    public static PdfTheme Create() => new()
    {
        Key = "classic",
        BudgetPageSize = PageSize.A4,
        BookkeepingPageSize = PageSize.A4.Rotate(),
        MarginTop = Mm(29),
        MarginRight = Mm(29),
        MarginBottom = Mm(22),
        MarginLeft = Mm(29),
        BookkeepingMarginTop = Mm(18),
        BookkeepingMarginRight = Mm(14),
        BookkeepingMarginBottom = Mm(15),
        BookkeepingMarginLeft = Mm(14),
        TitleFontSize = 14,
        SubtitleFontSize = 14,
        BodyFontSize = 6.8f,
        BookkeepingBodyFontSize = 6.4f,
        BookkeepingHeaderFontSize = 6.1f,
        HeaderFontSize = 6.8f,
        FooterFontSize = 7,
        SectionFill = Rgb(164, 164, 164),
        SectionTextColor = Rgb(0, 0, 0),
        HeaderFill = Rgb(215, 215, 215),
        SummaryFill = Rgb(215, 215, 215),
        BorderColor = Rgb(126, 126, 126),
        TextColor = Rgb(0, 0, 0),
        MutedTextColor = Rgb(89, 89, 89),
        AccentColor = Rgb(95, 95, 95),
        WatermarkColor = Rgb(210, 210, 210),
        BorderWidth = 0.55f,
        CellPadding = 2.8f,
        HeaderMetaPanel = false,
        FooterShowsTotalPages = true,
        FooterTopRule = false,
        BudgetTable = new PdfTableVisualSpec
        {
            SectionMarginTop = Mm(5),
            SectionFontSize = 9,
            SectionLineHeight = 1.12f,
            SectionPaddingTop = Mm(0.35f),
            SectionPaddingBottom = Mm(0.35f),
            SectionPaddingHorizontal = Mm(1.55f),
            DateFontSize = 6.8f,
            DateLineHeight = 1.2f,
            DatePaddingTop = Mm(0.12f),
            DatePaddingBottom = Mm(0.12f),
            DatePaddingHorizontal = Mm(1.55f),
            DateUnderline = true,
            DateBorderTopWidth = 0,
            DateBorderBottomWidth = 0,
            HeaderFontSize = 6.8f,
            HeaderLineHeight = 1.18f,
            HeaderPaddingVertical = Mm(0.12f),
            HeaderPaddingHorizontal = Mm(1.55f),
            HeaderDividerWidth = Mm(0.2f),
            HeaderBottomBorderWidth = 0,
            BodyFontSize = 6.8f,
            BodyLineHeight = 1.32f,
            BodyPaddingVertical = Mm(0.12f),
            BodyPaddingHorizontal = Mm(1.55f),
            BodyBottomBorderWidth = 0,
            SummaryTopBorderWidth = Mm(0.35f),
            SummaryFirstTopBorderWidth = Mm(0.35f),
            MoneySecondaryFontSize = 6,
        },
        BookkeepingTable = new PdfTableVisualSpec
        {
            SectionMarginTop = Mm(5),
            SectionFontSize = 9,
            SectionLineHeight = 1.12f,
            SectionPaddingTop = Mm(0.35f),
            SectionPaddingBottom = Mm(0.35f),
            SectionPaddingHorizontal = Mm(1.15f),
            DateFontSize = 6.4f,
            DateLineHeight = 1.2f,
            DatePaddingTop = Mm(0.12f),
            DatePaddingBottom = Mm(0.12f),
            DatePaddingHorizontal = Mm(1.15f),
            DateUnderline = true,
            DateBorderTopWidth = 0,
            DateBorderBottomWidth = 0,
            HeaderFontSize = 6.1f,
            HeaderLineHeight = 1.14f,
            HeaderPaddingVertical = Mm(0.12f),
            HeaderPaddingHorizontal = Mm(1.15f),
            HeaderDividerWidth = Mm(0.2f),
            HeaderBottomBorderWidth = 0,
            BodyFontSize = 6.4f,
            BodyLineHeight = 1.24f,
            BodyPaddingVertical = Mm(0.12f),
            BodyPaddingHorizontal = Mm(1.15f),
            BodyBottomBorderWidth = 0,
            SummaryTopBorderWidth = Mm(0.2f),
            SummaryFirstTopBorderWidth = Mm(0.35f),
            MoneySecondaryFontSize = 5.8f,
        },
        Signature = new PdfSignatureVisualSpec
        {
            FullWidthMm = 152,
            MarginTop = Mm(4),
            SectionTopBorderWidth = 0,
            TitleFontSize = 9,
            TitleLineHeight = 1.12f,
            TitleMinHeightMm = 6,
            TitlePaddingTopMm = 0.8f,
        },
    };
}
