using static BudgetCentre.PdfRenderer.Theme.PdfThemePrimitives;

namespace BudgetCentre.PdfRenderer.Theme;

internal static class StatementRedTheme
{
    public static PdfTheme Create() => ClassicTheme.Create() with
    {
        Key = "statement_red",
        MarginTop = Mm(18),
        MarginRight = Mm(16),
        MarginBottom = Mm(16),
        MarginLeft = Mm(16),
        BookkeepingMarginTop = Mm(14),
        BookkeepingMarginRight = Mm(12),
        BookkeepingMarginBottom = Mm(15),
        BookkeepingMarginLeft = Mm(12),
        TitleFontSize = 20,
        SubtitleFontSize = 8.2f,
        BodyFontSize = 7,
        BookkeepingBodyFontSize = 6.25f,
        BookkeepingHeaderFontSize = 6.1f,
        HeaderFontSize = 7,
        SectionFill = Rgb(157, 157, 157),
        SectionTextColor = Rgb(0, 0, 0),
        HeaderFill = Rgb(217, 217, 217),
        SummaryFill = Rgb(255, 255, 255),
        BorderColor = Rgb(17, 17, 17),
        AccentColor = Rgb(219, 0, 17),
        WatermarkColor = Rgb(224, 224, 224),
        HeaderMetaPanel = true,
        FooterShowsTotalPages = false,
        BudgetTable = new PdfTableVisualSpec
        {
            SectionMarginTop = Mm(5.5f),
            SectionFontSize = 10.4f,
            SectionLineHeight = 1.12f,
            SectionPaddingTop = Mm(0.6f),
            SectionPaddingBottom = Mm(0.55f),
            SectionPaddingHorizontal = Mm(1.35f),
            DateFontSize = 7.2f,
            DateLineHeight = 1.22f,
            DatePaddingTop = Mm(1.6f),
            DatePaddingBottom = Mm(0.8f),
            DatePaddingHorizontal = Mm(1.35f),
            DateUnderline = true,
            DateBorderTopWidth = 0,
            DateBorderBottomWidth = 0,
            HeaderFontSize = 7,
            HeaderLineHeight = 1.16f,
            HeaderPaddingVertical = Mm(0.25f),
            HeaderPaddingHorizontal = Mm(1.35f),
            HeaderDividerWidth = Mm(0.2f),
            HeaderBottomBorderWidth = 0,
            BodyFontSize = 7,
            BodyLineHeight = 1.24f,
            BodyPaddingVertical = Mm(0.25f),
            BodyPaddingHorizontal = Mm(1.35f),
            BodyBottomBorderWidth = 0,
            SummaryTopBorderWidth = Mm(0.35f),
            SummaryFirstTopBorderWidth = Mm(0.35f),
            MoneySecondaryFontSize = 6.2f,
        },
        BookkeepingTable = new PdfTableVisualSpec
        {
            SectionMarginTop = Mm(4.2f),
            SectionFontSize = 9,
            SectionLineHeight = 1.12f,
            SectionPaddingTop = Mm(0.42f),
            SectionPaddingBottom = Mm(0.42f),
            SectionPaddingHorizontal = Mm(1),
            DateFontSize = 6.2f,
            DateLineHeight = 1.2f,
            DatePaddingTop = Mm(0.18f),
            DatePaddingBottom = Mm(0.18f),
            DatePaddingHorizontal = Mm(1),
            DateUnderline = true,
            DateBorderTopWidth = 0,
            DateBorderBottomWidth = 0,
            HeaderFontSize = 6.1f,
            HeaderLineHeight = 1.14f,
            HeaderPaddingVertical = Mm(0.18f),
            HeaderPaddingHorizontal = Mm(1),
            HeaderDividerWidth = Mm(0.2f),
            HeaderBottomBorderWidth = 0,
            BodyFontSize = 6.25f,
            BodyLineHeight = 1.2f,
            BodyPaddingVertical = Mm(0.18f),
            BodyPaddingHorizontal = Mm(1),
            BodyBottomBorderWidth = 0,
            SummaryTopBorderWidth = Mm(0.2f),
            SummaryFirstTopBorderWidth = Mm(0.35f),
            MoneySecondaryFontSize = 5.7f,
        },
        Signature = new PdfSignatureVisualSpec
        {
            FullWidthMm = 178,
            MarginTop = Mm(5.5f),
            SectionTopBorderWidth = 0,
            TitleFontSize = 10.4f,
            TitleLineHeight = 1.12f,
            TitleMinHeightMm = 6,
            TitlePaddingTopMm = 0.8f,
        },
    };
}
