CREATE TABLE IF NOT EXISTS budget_bookkeeping_records (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  budget_id BIGINT UNSIGNED NOT NULL,
  transaction_type VARCHAR(32) NOT NULL DEFAULT 'expense',
  record_date DATE NULL,
  order_reference VARCHAR(120) NULL,
  details VARCHAR(500) NOT NULL,
  category_label VARCHAR(160) NULL,
  source_account_name VARCHAR(160) NULL,
  destination_account_name VARCHAR(160) NULL,
  currency_id BIGINT UNSIGNED NOT NULL,
  amount_original DECIMAL(18, 4) NOT NULL,
  rate_to_base DECIMAL(20, 10) NOT NULL DEFAULT 1,
  amount_base DECIMAL(18, 4) NOT NULL,
  destination_currency_id BIGINT UNSIGNED NULL,
  destination_amount_original DECIMAL(18, 4) NULL,
  destination_rate DECIMAL(20, 10) NULL,
  remark VARCHAR(500) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_budget_bookkeeping_records_budget (budget_id),
  KEY idx_budget_bookkeeping_records_type (transaction_type),
  CONSTRAINT fk_budget_bookkeeping_records_budget FOREIGN KEY (budget_id) REFERENCES budgets(id) ON DELETE CASCADE,
  CONSTRAINT fk_budget_bookkeeping_records_currency FOREIGN KEY (currency_id) REFERENCES currencies(id),
  CONSTRAINT fk_budget_bookkeeping_records_destination_currency FOREIGN KEY (destination_currency_id) REFERENCES currencies(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
