SET NAMES utf8mb4;

INSERT INTO currencies (code, name, symbol, decimal_places, is_enabled)
VALUES
  ('AFN', 'AFGHANISTAN AFGHANI', 'AFN', 0, 1),
  ('ALL', 'ALBANIAN LEK', 'ALL', 0, 1),
  ('DZD', 'ALGERIAN DINAR', 'DZD', 2, 1),
  ('AOA', 'ANGOLAN KWANZA', 'AOA', 2, 1),
  ('ARS', 'ARGENTINE PESO', 'ARS', 2, 1),
  ('AMD', 'ARMENIAN DRAM', 'AMD', 2, 1),
  ('AWG', 'ARUBAN GUILDER', 'AWG', 2, 1),
  ('AUD', 'AUSTRALIAN DOLLAR', 'AUD', 2, 1),
  ('AZN', 'AZERBAIJAN MANAT', 'AZN', 2, 1),
  ('BSD', 'BAHAMIAN DOLLAR', 'BSD', 2, 1),
  ('BHD', 'BAHRAIN DINAR', 'BHD', 3, 1),
  ('BDT', 'BANGLADESH TAKA', 'BDT', 2, 1),
  ('BBD', 'BARBADOS DOLLAR', 'BBD', 2, 1),
  ('BYN', 'BELARUSSIAN RUBLE', 'BYN', 2, 1),
  ('BZD', 'BELIZE DOLLAR', 'BZD', 2, 1),
  ('BMD', 'BERMUDAN DOLLAR', 'BMD', 2, 1),
  ('BTN', 'BHUTANESE NGULTRUM', 'BTN', 2, 1),
  ('BOB', 'BOLIVIAN BOLIVIANO', 'BOB', 2, 1),
  ('BAM', 'BOSNIAN CONVERTIBLE MARK', 'BAM', 2, 1),
  ('BWP', 'BOTSWANA PULA', 'BWP', 2, 1),
  ('BRL', 'BRAZILIAN REAL', 'BRL', 2, 1),
  ('BND', 'BRUNEI DOLLAR', 'BND', 2, 1),
  ('BIF', 'BURUNDI FRANC', 'BIF', 0, 1),
  ('KHR', 'CAMBODIAN RIEL', 'KHR', 2, 1),
  ('CAD', 'CANADIAN DOLLAR', 'CAD', 2, 1),
  ('CVE', 'CAPE VERDE ESCUDO', 'CVE', 2, 1),
  ('XCG', 'CARIBBEAN GUILDER', 'XCG', 2, 1),
  ('KYD', 'CAYMAN ISLAND DOLLAR', 'KYD', 2, 1),
  ('XOF', 'CFA FRANC BCEAO', 'XOF', 0, 1),
  ('XAF', 'CFA FRANC BEAC', 'XAF', 0, 1),
  ('XPF', 'CFP FRANC', 'XPF', 0, 1),
  ('CLP', 'CHILEAN PESO', 'CLP', 0, 1),
  ('CNY', 'CHINA YUAN RENMINBI', 'CNY', 2, 1),
  ('COP', 'COLOMBIAN PESO', 'COP', 0, 1),
  ('KMF', 'COMOROS FRANC', 'KMF', 0, 1),
  ('CDF', 'CONGOLESE FRANC', 'CDF', 2, 1),
  ('CRC', 'COSTA RICA COLON', 'CRC', 2, 1),
  ('CUP', 'CUBAN PESO', 'CUP', 2, 1),
  ('CZK', 'CZECH KORUNA', 'CZK', 2, 1),
  ('DKK', 'DANISH KRONE', 'DKK', 2, 1),
  ('DJF', 'DJIBOUTI FRANC', 'DJF', 0, 1),
  ('DOP', 'DOMINICAN PESO', 'DOP', 2, 1),
  ('XCD', 'EAST CARIBBEAN DOLLAR', 'XCD', 2, 1),
  ('EGP', 'EGYPTIAN POUND', 'EGP', 2, 1),
  ('SVC', 'EL SALVADOR COLON', 'SVC', 2, 1),
  ('ETB', 'ETHIOPIA BIRR', 'ETB', 2, 1),
  ('EUR', 'EURO', 'EUR', 2, 1),
  ('FKP', 'FALKLAND ISLAND POUND', 'FKP', 2, 1),
  ('FJD', 'FIJI DOLLAR', 'FJD', 2, 1),
  ('GMD', 'GAMBIA DALASI', 'GMD', 2, 1),
  ('GEL', 'GEORGIAN LARI', 'GEL', 2, 1),
  ('GHS', 'GHANAIAN CEDI', 'GHS', 2, 1),
  ('GIP', 'GIBRALTAR POUND', 'GIP', 2, 1),
  ('GBP', 'GREAT BRITISH POUND', 'GBP', 2, 1),
  ('GTQ', 'GUATEMALA QUETZAL', 'GTQ', 2, 1),
  ('GNF', 'GUINEA FRANC', 'GNF', 0, 1),
  ('GYD', 'GUYANA DOLLAR', 'GYD', 2, 1),
  ('HTG', 'HAITI GOURDE', 'HTG', 2, 1),
  ('HNL', 'HONDURAS LEMPIRA', 'HNL', 2, 1),
  ('HKD', 'HONG KONG DOLLAR', 'HKD', 2, 1),
  ('HUF', 'HUNGARIAN FORINT', 'HUF', 0, 1),
  ('ISK', 'ICELANDIC KRONA', 'ISK', 0, 1),
  ('INR', 'INDIAN RUPEE', 'INR', 2, 1),
  ('IDR', 'INDONESIAN RUPIAH', 'IDR', 0, 1),
  ('IQD', 'IRAQ DINAR', 'IQD', 0, 1),
  ('ILS', 'ISRAELI SHEQEL', 'ILS', 2, 1),
  ('JMD', 'JAMAICAN DOLLAR', 'JMD', 2, 1),
  ('JPY', 'JAPANESE YEN', 'JPY', 0, 1),
  ('JOD', 'JORDAN DINAR', 'JOD', 3, 1),
  ('KZT', 'KAZAKHSTAN TENGE', 'KZT', 2, 1),
  ('KES', 'KENYAN SHILLING', 'KES', 2, 1),
  ('KWD', 'KUWAITI DINAR', 'KWD', 3, 1),
  ('KGS', 'KYRGYZSTAN SOM', 'KGS', 2, 1),
  ('LAK', 'LAOTIAN KIP', 'LAK', 0, 1),
  ('LBP', 'LEBANESE POUND', 'LBP', 0, 1),
  ('LSL', 'LESOTHO LOTI', 'LSL', 2, 1),
  ('LRD', 'LIBERIAN DOLLAR', 'LRD', 2, 1),
  ('LYD', 'LIBYA DINAR', 'LYD', 3, 1),
  ('MOP', 'MACAU PATACA', 'MOP', 2, 1),
  ('MKD', 'MACEDONIA DENAR', 'MKD', 2, 1),
  ('MGA', 'MALAGASCY ARIARY', 'MGA', 0, 1),
  ('MWK', 'MALAWI KWACHA', 'MWK', 2, 1),
  ('MYR', 'MALAYSIAN RINGGIT', 'MYR', 2, 1),
  ('MVR', 'MALDIVE RUFIYAA', 'MVR', 2, 1),
  ('MRU', 'MAURITANIA OUGUIYA NEW', 'MRU', 2, 1),
  ('MUR', 'MAURITIAN RUPEE', 'MUR', 2, 1),
  ('MXN', 'MEXICAN PESO', 'MXN', 2, 1),
  ('MDL', 'MOLDOVA LEU', 'MDL', 2, 1),
  ('MNT', 'MONGOLIA TUGRIK', 'MNT', 2, 1),
  ('MAD', 'MOROCCAN DIRHAM', 'MAD', 2, 1),
  ('MZN', 'MOZAMBIQUE METICAL', 'MZN', 2, 1),
  ('MMK', 'MYANMAR KYAT', 'MMK', 0, 1),
  ('NAD', 'NAMIBIA DOLLAR', 'NAD', 2, 1),
  ('NPR', 'NEPALESE RUPEE', 'NPR', 2, 1),
  ('NZD', 'NEW ZEALAND DOLLAR', 'NZD', 2, 1),
  ('NIO', 'NICARAGUA CORDOBA ORO', 'NIO', 2, 1),
  ('NGN', 'NIGERIAN NAIRA', 'NGN', 2, 1),
  ('NOK', 'NORWEGIAN KRONE', 'NOK', 2, 1),
  ('OMR', 'OMAN RIAL', 'OMR', 3, 1),
  ('PKR', 'PAKISTANI RUPEE', 'PKR', 0, 1),
  ('PAB', 'PANAMA BALBOA', 'PAB', 2, 1),
  ('PGK', 'PAPUA NEW GUINEA KINA', 'PGK', 2, 1),
  ('PYG', 'PARAGUAY GUARANI', 'PYG', 0, 1),
  ('PEN', 'PERU NUEVO SOL', 'PEN', 2, 1),
  ('PHP', 'PHILIPPINE PESO', 'PHP', 2, 1),
  ('PLN', 'POLISH ZLOTY', 'PLN', 2, 1),
  ('QAR', 'QATAR RIAL', 'QAR', 2, 1),
  ('RON', 'ROMANIAN LEU', 'RON', 2, 1),
  ('RUB', 'RUSSIAN RUBLE', 'RUB', 2, 1),
  ('RWF', 'RWANDA FRANC', 'RWF', 0, 1),
  ('SHP', 'SAINT HELENA POUND', 'SHP', 2, 1),
  ('WST', 'SAMOA TALA', 'WST', 2, 1),
  ('STN', 'SAO TOME ANDPRINCIPE DOBRA NEW', 'STN', 2, 1),
  ('SAR', 'SAUDI ARABIA RIYAL', 'SAR', 2, 1),
  ('RSD', 'SERBIAN DINAR', 'RSD', 2, 1),
  ('SCR', 'SEYCHELLES RUPEE', 'SCR', 2, 1),
  ('SLE', 'SIERRA LEONE SLE', 'SLE', 2, 1),
  ('SGD', 'SINGAPORE DOLLAR', 'SGD', 2, 1),
  ('SBD', 'SOLOMON ISLAND DOLLAR', 'SBD', 2, 1),
  ('SOS', 'SOMALI SHILLING', 'SOS', 0, 1),
  ('ZAR', 'SOUTH AFRICAN RAND', 'ZAR', 2, 1),
  ('KRW', 'SOUTH KOREAN WON', 'KRW', 0, 1),
  ('SSP', 'SOUTH SUDAN POUND', 'SSP', 2, 1),
  ('LKR', 'SRI LANKAN RUPEE', 'LKR', 2, 1),
  ('SDG', 'SUDANESE POUND', 'SDG', 2, 1),
  ('SRD', 'SURINAME DOLLAR', 'SRD', 2, 1),
  ('SZL', 'SWAZILAND LILANGENI', 'SZL', 2, 1),
  ('SEK', 'SWEDISH KRONA', 'SEK', 2, 1),
  ('CHF', 'SWISS FRANC', 'CHF', 2, 1),
  ('TWD', 'TAIWAN DOLLAR', 'TWD', 2, 1),
  ('TJS', 'TAJIKISTAN SOMONI', 'TJS', 2, 1),
  ('TZS', 'TANZANIAN SHILLING', 'TZS', 2, 1),
  ('THB', 'THAI BAHT', 'THB', 2, 1),
  ('TOP', 'TONGA PAANGA', 'TOP', 2, 1),
  ('TTD', 'TRINIDAD AND TOGABO DOLLAR', 'TTD', 2, 1),
  ('TND', 'TUNISIAN DINAR', 'TND', 3, 1),
  ('TRY', 'TURKISH LIRA', 'TRY', 2, 1),
  ('TMT', 'TURKMENISTAN MANAT', 'TMT', 2, 1),
  ('UGX', 'UGANDA SHILLING', 'UGX', 0, 1),
  ('UAH', 'UKRAINIAN HRYVNIA', 'UAH', 2, 1),
  ('AED', 'UNITED ARAB EMIRATES DIRHAM', 'AED', 2, 1),
  ('USD', 'UNITED STATES DOLLAR', 'USD', 2, 1),
  ('UYU', 'URUGUAY PESO', 'UYU', 2, 1),
  ('UZS', 'UZBEKISTAN SUM', 'UZS', 2, 1),
  ('VUV', 'VANUATU VATU', 'VUV', 0, 1),
  ('VES', 'VENEZUELAN BOLIVAR SOBERANO', 'VES', 2, 1),
  ('VND', 'VIETNAM DONG', 'VND', 0, 1),
  ('YER', 'YEMEN RIAL', 'YER', 0, 1),
  ('ZMW', 'ZAMBIA KWACHA', 'ZMW', 2, 1),
  ('ZWG', 'ZIMBABWE GOLD', 'ZWG', 2, 1)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  symbol = CASE WHEN symbol IS NULL OR symbol = '' OR symbol = code THEN VALUES(symbol) ELSE symbol END,
  decimal_places = VALUES(decimal_places),
  is_enabled = 1;
